apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: <+serviceVariables.replicas>
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: <+artifact.image>
          ports:
            - containerPort: 3000
          env:
            - name: HELLO_MESSAGE
              value: <+serviceVariables.hello_message>
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
